/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GenealogyRouteImport } from './routes/genealogy'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GenealogyRoute = GenealogyRouteImport.update({
  id: '/genealogy',
  path: '/genealogy',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/genealogy': typeof GenealogyRoute
  '/glossary': typeof GlossaryRoute
  '/maps': typeof MapsRoute
  '/quiz': typeof QuizRoute
  '/references': typeof ReferencesRoute
  '/timeline': typeof TimelineRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/genealogy': typeof GenealogyRoute
  '/glossary': typeof GlossaryRoute
  '/maps': typeof MapsRoute
  '/quiz': typeof QuizRoute
  '/references': typeof ReferencesRoute
  '/timeline': typeof TimelineRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/genealogy': typeof GenealogyRoute
  '/glossary': typeof GlossaryRoute
  '/maps': typeof MapsRoute
  '/quiz': typeof QuizRoute
  '/references': typeof ReferencesRoute
  '/timeline': typeof TimelineRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/genealogy'
    | '/glossary'
    | '/maps'
    | '/quiz'
    | '/references'
    | '/timeline'
    | '/chapters/$slug'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/genealogy'
    | '/glossary'
    | '/maps'
    | '/quiz'
    | '/references'
    | '/timeline'
    | '/chapters/$slug'
    | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/genealogy'
    | '/glossary'
    | '/maps'
    | '/quiz'
    | '/references'
    | '/timeline'
    | '/chapters/$slug'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  GenealogyRoute: typeof GenealogyRoute
  GlossaryRoute: typeof GlossaryRoute
  MapsRoute: typeof MapsRoute
  QuizRoute: typeof QuizRoute
  ReferencesRoute: typeof ReferencesRoute
  TimelineRoute: typeof TimelineRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genealogy': {
      id: '/genealogy'
      path: '/genealogy'
      fullPath: '/genealogy'
      preLoaderRoute: typeof GenealogyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  GenealogyRoute: GenealogyRoute,
  GlossaryRoute: GlossaryRoute,
  MapsRoute: MapsRoute,
  QuizRoute: QuizRoute,
  ReferencesRoute: ReferencesRoute,
  TimelineRoute: TimelineRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
